
-- 1. What are the details of all cars purchased in the year 2022?

SELECT *
FROM cars; 


-- 2. What is the total number of cars sold by each salesperson?

SELECT s.salesman_id,
p.name,
COUNT(sale_id) AS Sales
FROM sales s 
LEFT JOIN salespersons p
ON  p.salesman_id =s.salesman_id
GROUP BY 1,2 ;

-- 3. What is the total revenue generated by each salesperson?

SELECT * FROM cars;

SELECT  s.salesman_id,
 p.name,

SUM(c.cost_$) as Profit_salesperson
FROM sales s 
LEFT JOIN salespersons p
ON  p.salesman_id =s.salesman_id
LEFT JOIN cars c
ON s.car_id = c.car_id
GROUP BY 1,2
;
-- 4.What are the details of the cars sold by each salesperson?

SELECT s.salesman_id,
p.name, 
c.car_id,
c.make,
c.type,
c.style,
c.cost_$ as Revenue
FROM sales s
LEFT JOIN cars c
ON s.car_id = c.car_id
LEFT JOIN salespersons p
ON s.salesman_id = p.salesman_id
ORDER BY s.salesman_id, c.car_id;

-- 5. What is the total revenue generated by each car type?

SELECT c.type,
SUM(c.cost_$) AS Revenue_type
FROM cars c
LEFT JOIN sales s
ON c.car_id = s.car_id
GROUP BY 1
ORDER BY Revenue_type DESC;

-- 6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT 
p.name, 
c.car_id,
c.make,
c.type,
c.style,
c.cost_$ as Revenue
FROM sales s
LEFT JOIN cars c
ON s.car_id = c.car_id
LEFT JOIN salespersons p
ON s.salesman_id = p.salesman_id
WHERE s.purchase_date LIKE '%2021%' AND  p.name = 'Emily Wong'
ORDER BY s.salesman_id, c.car_id;

-- 7. What is the total revenue generated by the sales of hatchback cars?

SELECT 
c.style,
SUM(c.cost_$)
FROM cars c
LEFT JOIN sales s
ON c.car_id = s.car_id
WHERE c.car_id = 2
GROUP BY 1
;

-- 8. What is the total revenue generated by the sales of SUV cars in the year 2022?
SELECT * FROM sales;

SELECT 
c.style,
SUM(c.cost_$) AS SUV_Revenue
FROM cars c
LEFT JOIN sales s
ON c.car_id = s.car_id
WHERE c.style = 'SUV' AND s.purchase_date LIKE ('%2022%')
GROUP BY 1; 

-- 9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT p.name,
p.city,
COUNT(s.sale_id) AS Sales
FROM sales s
LEFT JOIN salespersons p
ON s.salesman_id = p.salesman_id
WHERE YEAR(s.purchase_date) = '2023' 
GROUP BY 1,2
ORDER BY Sales DESC
LIMIT 1;

-- 10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT p.name,
p.age,
SUM(c.cost_$) AS Sales
FROM cars c
LEFT JOIN sales s
ON c.car_id = s.car_id
LEFT JOIN salespersons p
ON s.salesman_id = p.salesman_id
WHERE YEAR(s.purchase_date) = '2022'
GROUP BY 1,2
ORDER BY Sales DESC 
LIMIT 1;
